[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
test = false

[dependencies]
bootloader_api = "0.11.4"
noto-sans-mono-bitmap = "0.2.0"
spin = "0.9.8"
x86_64 = "0.14.10"
pic8259 = "0.10.4"
pc-keyboard = "0.7.0"
paste = "1.0"
